### ISSUE TITLE
Display near alloy matches, including along side the result, if any

### ISSUE THREAD

**Issue by unforbidable** [unforbidable/tfc-ore-calc#1]

**Comment by HalfInt** [comment]
Let me suggest an easier to implement variant:
The user selects the target alloy. Then show "to little/to much" for each ingredient.
This feature can be extended to also serve as recipe reminder: Automatically add lines for each of the ingredients required for the selected alloy. You can show the allowed range, too.

**Comment by unforbidable** [comment]
That is interesting, but very difficult to do in a way that could be useful, because of all the different ore yields. In other words, the calculator could suggest using rich when the player has only normal or poor. 

Thanks for the tip. I added an option to fill the rows with specific metals, just not the actual values, and suggestions box, that can be used as a reminder. I think I am happy with that, may revisit if something comes up. I hope this works for now.

**Comment by HalfInt** [comment]
Great work! The suggestions box effectively does what I was going for.
Would be nice though, if it kept showing when valid ratios are met, so you can still see the the possible ranges.
